// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkruI80Pytzax030Nn-5Xjv1srxAlIZ30',
    appId: '1:919531585783:web:28471a6d58806e0e1413f2',
    messagingSenderId: '919531585783',
    projectId: 'kezek-in',
    authDomain: 'kezek-in.firebaseapp.com',
    storageBucket: 'kezek-in.firebasestorage.app',
    measurementId: 'G-J5JDY7HR8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS2FXTz-qpSwQPYJu24PSkYueglIKTeEg',
    appId: '1:919531585783:android:023de68cd566aecc1413f2',
    messagingSenderId: '919531585783',
    projectId: 'kezek-in',
    storageBucket: 'kezek-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqeTsi6OzBVTOr9njR7grt1qRnCEb0n8',
    appId: '1:919531585783:ios:736c26199cbdfc281413f2',
    messagingSenderId: '919531585783',
    projectId: 'kezek-in',
    storageBucket: 'kezek-in.firebasestorage.app',
    iosBundleId: 'com.example.kezekIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqeTsi6OzBVTOr9njR7grt1qRnCEb0n8',
    appId: '1:919531585783:ios:736c26199cbdfc281413f2',
    messagingSenderId: '919531585783',
    projectId: 'kezek-in',
    storageBucket: 'kezek-in.firebasestorage.app',
    iosBundleId: 'com.example.kezekIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkruI80Pytzax030Nn-5Xjv1srxAlIZ30',
    appId: '1:919531585783:web:8c55f798c2f84d6c1413f2',
    messagingSenderId: '919531585783',
    projectId: 'kezek-in',
    authDomain: 'kezek-in.firebaseapp.com',
    storageBucket: 'kezek-in.firebasestorage.app',
    measurementId: 'G-JE575DW5P5',
  );
}
